# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 127.0.0.1:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "/etc/prometheus/rules/up-node_exporter.yml"
  # - "prometheus.rules.yml"
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ['localhost:9100']

  - job_name: "redis_exporter"
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:9121']

  - job_name: "mongodb_exporter"
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:9103']

  - job_name: "mysql"
    static_configs:
    - targets: ['127.0.0.1:9104']

  - job_name: "nginx-vts-exporter"
    static_configs:
    - targets: ['127.0.0.1:9913']

  - job_name: 'nginx-prometheus-exporter'
    static_configs:
    - targets: ['127.0.0.1:9113']

  # docker
  # - job_name: 'cadvisor'
  #   static_configs:
  #   - targets: ['127.0.0.1:8080']

  # - job_name: 'blackbox_http'
  #   metrics_path: /probe
  #   params:
  #     module: [http_2xx]
  #
  #   static_configs:
  #     - targets:
  #       - http://prometheus.io
  #       - https://prometheus.io
  #       - http://www.baidu.com
  #   relabel_configs:
  #     - source_labels: [__address__]
  #       target_label: __param_target
  #     - source_labels: [__param_target]
  #       target_label: instance
  #     - target_label: __address__
  #       replacement: 127.0.0.1:9115

  - job_name: 'blackbox_exporter'  # collect blackbox exporter's operational metrics.
    static_configs:
      - targets: ['127.0.0.1:9115']

  - job_name: "nvidia"
    static_configs:
    - targets: ['127.0.0.1:9445']

  - job_name: "github"
    static_configs:
    - targets: ['127.0.0.1:9171']

  - job_name: 'android'
    static_configs:
    - targets: ['192.168.1.111:9120']
      labels:
        machine: 'mi10'

  - job_name: 'Alertmanager'
    static_configs:
    - targets: ['127.0.0.1:9093']

  - job_name: 'mtail'
    static_configs:
    - targets: ['127.0.0.1:3903']

  # - job_name: 'consul_sd_node_exporter'
  #   scheme: http
  #   consul_sd_configs:
  #     - server: 127.0.0.1:8500
  #       services: ['node_exporter']
